version: '3.8'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=database_ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - database_ignite

volumes:
  pgdata:
    driver: local
